/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author apurvazawar
 */
public class ViewPersonDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonDirectoryJPanel
     */
    PersonDirectory personDirectoryArrayList;
    DefaultTableModel defaultTableModel;
    int row, column;
    
    public ViewPersonDirectoryJPanel(PersonDirectory personDirectoryArrayList) {
        initComponents();
        this.personDirectoryArrayList = personDirectoryArrayList;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableViewPersonDirectory = new javax.swing.JTable();
        lblPersonDirectory = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jTableViewPersonDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Gender", "Contact Number", "Residence", "Community", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableViewPersonDirectory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableViewPersonDirectoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableViewPersonDirectory);

        lblPersonDirectory.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblPersonDirectory.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonDirectory.setText("Person Directory ");
        lblPersonDirectory.setSize(new java.awt.Dimension(45, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(lblPersonDirectory)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPersonDirectory)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableViewPersonDirectoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableViewPersonDirectoryMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableViewPersonDirectoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableViewPersonDirectory;
    private javax.swing.JLabel lblPersonDirectory;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        defaultTableModel = (DefaultTableModel)jTableViewPersonDirectory.getModel();
        defaultTableModel.setRowCount(0);
        
        for(Person person : personDirectoryArrayList.getPersonDirectoryArrayList()){
            Object[] row = new Object[8];
            row[0]= person.getId();
            row[1]= person;
            row[2]= person.getPersonAge();
            row[3]= person.getGender();
            row[4]= person.getContactNumber();
            row[5]= person.getHouseAddress();
            row[6]= person.getCommunityName();
            row[7]= person.getCityName();
            defaultTableModel.addRow(row); 
        }
    }
}
